[workspace]
members = [
    "telbot-types",
    "telbot-cf-worker",
    "telbot-cf-worker/examples/get-me",
    "telbot-cf-worker/examples/echo",
    "telbot-cf-worker/examples/file",
    "telbot-ureq",
    "telbot-hyper",
]
